#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 OUTPUT_PARENT MEMO_Z3_CACHE" >&2
  exit 2
fi

readonly OUTPUT_PARENT="$1"
readonly Z3_CACHE="$2"
readonly SAIL_VERSION="0.20.2"
readonly LEAN_SAIL_REPOSITORY="https://github.com/rems-project/lean-sail.git"
readonly LEAN_SAIL_COMMIT="79b4d08505af29d88b3918f32d29840fae1fa191"
readonly LEAN_SAIL_DIRECTORY="lean-sail"
readonly UPSTREAM_BASE_TAG="0.13.1"
readonly UPSTREAM_BASE_COMMIT="27224ccb2290f022e46213c05b3e72e8a9ea635e"
readonly OCAML_VERSION="5.2.1"
readonly Z3_VERSION="4.8.12"
readonly CONFIG_SHA256="8a9d974bc9547a0ea777b4b227a8efbd1ef0352e183653f16a6d8983ff05ad65"
readonly LEAN_TOOLCHAIN="leanprover/lean4:v4.34.0"
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
readonly CONFIG="$SCRIPT_DIR/openvm.json"
readonly STAGING="/tmp/sail-riscv-openvm"
readonly SOURCE_PROVENANCE_NAME="sail-source-provenance.tsv"
readonly PACKAGE_LICENSE_NAME="lean-package-LICENSE"
readonly LEAN_MODULE_HEADER='-- This file is part of the OpenVM Sail RISC-V Lean model. It was generated by the
-- Sail compiler from the OpenVM adaptation of the Sail RISC-V architecture model and
-- is subject to the BSD two-clause licence in the LICENSE file of this package.
--
-- SPDX-License-Identifier: BSD-2-Clause'
readonly SOURCE_INPUTS=(
  handwritten_support/RiscvExtrasExecutable.lean
  model/riscv.sail_project
  model/core/callbacks.sail
  model/core/extensions.sail
  model/postlude/fetch.sail
  model/postlude/device_tree.sail
  model/postlude/step.sail
  model/postlude/step_ext.sail
  model/sys/sys_control.sail
  model/openvm/openvm.json
  model/openvm/openvm.sail_project
  model/openvm/openvm_profile.sail
  model/extensions/Xopenvm/xopenvm.sail_project
  model/extensions/Xopenvm/xopenvm_insts.sail
  model/openvm/generate-lean.sh
  model/openvm/lean-sail-compat.patch
  model/openvm/lean-package-LICENSE
)

write_source_provenance() {
  local output="$1"
  local source_commit source_tree source_input source_sha
  source_commit="$(git -C "$REPOSITORY" rev-parse HEAD)"
  source_tree="$(git -C "$REPOSITORY" rev-parse 'HEAD^{tree}')"

  {
    printf 'format\t1\n'
    printf 'sail_source_commit\t%s\n' "$source_commit"
    printf 'sail_source_tree\t%s\n' "$source_tree"
    printf 'upstream_base_tag\t%s\n' "$UPSTREAM_BASE_TAG"
    printf 'upstream_base_commit\t%s\n' "$UPSTREAM_BASE_COMMIT"
    printf 'sail_compiler_version\t%s\n' "$SAIL_VERSION"
    printf 'lean_sail_source_commit\t%s\n' "$LEAN_SAIL_COMMIT"
    printf 'lean_sail_compatibility\tLean v4.34.0\n'
    printf 'ocaml_version\t%s\n' "$OCAML_VERSION"
    printf 'z3_version\t%s\n' "$Z3_VERSION"
    printf 'generation_config_sha256\t%s\n' "$CONFIG_SHA256"
    printf 'lean_toolchain\t%s\n' "$LEAN_TOOLCHAIN"
    for source_input in "${SOURCE_INPUTS[@]}"; do
      source_sha="$(git -C "$REPOSITORY" show "HEAD:$source_input" | sha256sum | cut -d ' ' -f 1)"
      printf 'input_sha256\t%s\t%s\n' "$source_sha" "$source_input"
    done
  } > "$output"
}

if [[ -e "$STAGING" ]]; then
  echo "staging path already exists: $STAGING" >&2
  exit 1
fi
mkdir "$STAGING"

cleanup() {
  rm -rf "$STAGING"
}
trap cleanup EXIT

for source_input in "${SOURCE_INPUTS[@]}"; do
  if ! git -C "$REPOSITORY" cat-file -e "HEAD:$source_input" 2>/dev/null; then
    echo "generation input is not committed at HEAD: $source_input" >&2
    exit 1
  fi
done
if [[ "$(sha256sum "$CONFIG" | cut -d ' ' -f 1)" != "$CONFIG_SHA256" ]]; then
  echo "unexpected generation config" >&2
  exit 1
fi

if [[ "$(ocamlc -version)" != "$OCAML_VERSION" ]]; then
  echo "unexpected OCaml version: $(ocamlc -version)" >&2
  exit 1
fi
if [[ "$(sail --version)" != "Sail $SAIL_VERSION "* ]]; then
  echo "unexpected Sail compiler: $(sail --version)" >&2
  exit 1
fi
if [[ "$(z3 --version)" != "Z3 version $Z3_VERSION "* ]]; then
  echo "unexpected Z3 version: $(z3 --version)" >&2
  exit 1
fi

# Generate from the committed HEAD (hermetic: uncommitted working-tree changes are
# ignored). HEAD is the single source+recipe commit; commit source edits first.
git -C "$REPOSITORY" archive HEAD | tar -x -C "$STAGING"

# required while the Sail pin is <= 0.20.2 — the released Lean backend does not emit the outer <Module> namespace (current master does); delete this strip when the pin moves to a namespace-emitting release.
cp "$STAGING/handwritten_support/RiscvExtrasExecutable.lean" "$STAGING/RiscvExtrasExecutable.lean"
sed -i '/^open THE_MODULE_NAME$/d' "$STAGING/RiscvExtrasExecutable.lean"

# Materialize the immutable lean-sail v4 runtime and apply the compatibility
# patch recorded alongside this recipe for the selected Lean compiler.
git clone --quiet "$LEAN_SAIL_REPOSITORY" "$STAGING/$LEAN_SAIL_DIRECTORY"
git -C "$STAGING/$LEAN_SAIL_DIRECTORY" checkout --quiet --detach "$LEAN_SAIL_COMMIT"
if [[ "$(git -C "$STAGING/$LEAN_SAIL_DIRECTORY" rev-parse HEAD)" != "$LEAN_SAIL_COMMIT" ]]; then
  echo "unexpected lean-sail source commit" >&2
  exit 1
fi
git -C "$STAGING/$LEAN_SAIL_DIRECTORY" apply \
  "$STAGING/model/openvm/lean-sail-compat.patch"

if [[ -e "$OUTPUT_PARENT/Lean_RV32D" ]]; then
  echo "output already exists: $OUTPUT_PARENT/Lean_RV32D" >&2
  exit 1
fi
mkdir -p "$OUTPUT_PARENT" "$(dirname "$Z3_CACHE")"
cd "$STAGING/model"

sail \
  -D OPENVM \
  --strict-var --strict-bitvector --strict-exponentials --require-version "$SAIL_VERSION" \
  --dno-error-filenames \
  --memo-z3-path "$Z3_CACHE" \
  --config openvm/openvm.json \
  --lean --memo-z3 --lean-output-dir "$OUTPUT_PARENT" --lean-force-output \
  --lean-lib-path "$LEAN_SAIL_DIRECTORY" \
  --lean-non-beq-type instruction --lean-non-beq-type ExecutionResult --lean-non-beq-type Step \
  --lean-import-file ../RiscvExtrasExecutable.lean -o Lean_RV32D \
  I_insts M_insts Xopenvm openvm_profile main \
  riscv.sail_project \
  extensions/Xopenvm/xopenvm.sail_project \
  openvm/openvm.sail_project

# Include every emitted module, including device-tree support outside the root import closure.
sed -i '/^name = "LeanRV32D"$/a globs = ["LeanRV32D", "LeanRV32D.+"]' \
  "$OUTPUT_PARENT/Lean_RV32D/lakefile.toml"
# Declare the package licence for Lake and Reservoir; the licence file itself is
# copied into the package below.
sed -i \
  -e '/^defaultTargets = \["LeanRV32D"\]$/a license = "BSD-2-Clause"' \
  -e '/^defaultTargets = \["LeanRV32D"\]$/a licenseFiles = ["LICENSE"]' \
  "$OUTPUT_PARENT/Lean_RV32D/lakefile.toml"

mkdir "$OUTPUT_PARENT/Lean_RV32D/$LEAN_SAIL_DIRECTORY"
cp "$STAGING/$LEAN_SAIL_DIRECTORY/Sail.lean" "$OUTPUT_PARENT/Lean_RV32D/$LEAN_SAIL_DIRECTORY/"
cp -R "$STAGING/$LEAN_SAIL_DIRECTORY/Sail" "$OUTPUT_PARENT/Lean_RV32D/$LEAN_SAIL_DIRECTORY/"
cat > "$OUTPUT_PARENT/Lean_RV32D/$LEAN_SAIL_DIRECTORY/lakefile.toml" <<'EOF'
name = "Sail"
defaultTargets = ["Sail"]
license = "BSD-2-Clause AND Apache-2.0"
licenseFiles = ["../LICENSE"]

[[lean_lib]]
name = "Sail"
leanOptions.weak.linter.style.nameCheck = false
EOF
# Record the path dependency in the generated manifest so a subsequent Lake
# build does not rewrite the attested package's dependency metadata.
cat > "$OUTPUT_PARENT/Lean_RV32D/lake-manifest.json" <<'EOF'
{"version": "1.2.0",
 "packagesDir": ".lake/packages",
 "packages":
 [{"type": "path",
   "scope": "",
   "name": "Sail",
   "manifestFile": "lake-manifest.json",
   "inherited": false,
   "dir": "lean-sail",
   "configFile": "lakefile.toml"}],
 "name": "Lean_RV32D",
 "lakeDir": ".lake",
 "fixedToolchain": false}
EOF
printf '%s\n' "$LEAN_TOOLCHAIN" > "$OUTPUT_PARENT/Lean_RV32D/$LEAN_SAIL_DIRECTORY/lean-toolchain"
printf '%s\n' "$LEAN_TOOLCHAIN" > "$OUTPUT_PARENT/Lean_RV32D/lean-toolchain"

# Ship the licence inside the package and mark every generated module, so the
# package remains licensed when Lean_RV32D is distributed on its own. The
# hand-written support module already carries its own licence header.
cp "$STAGING/model/openvm/$PACKAGE_LICENSE_NAME" "$OUTPUT_PARENT/Lean_RV32D/LICENSE"
for module in "$OUTPUT_PARENT/Lean_RV32D/LeanRV32D.lean" "$OUTPUT_PARENT/Lean_RV32D/LeanRV32D"/*.lean; do
  if ! grep -q '^-- *SPDX-License-Identifier:' "$module"; then
    { printf '%s\n\n' "$LEAN_MODULE_HEADER"; cat "$module"; } > "$module.tmp"
    mv "$module.tmp" "$module"
  fi
done
write_source_provenance "$OUTPUT_PARENT/Lean_RV32D/$SOURCE_PROVENANCE_NAME"
