// =======================================================================================
// This Sail RISC-V architecture model, comprising all files and
// directories except where otherwise noted is subject to the BSD
// two-clause license in the LICENSE file.
//
// SPDX-License-Identifier: BSD-2-Clause
// =======================================================================================

// ISA choices for the OpenVM model.
function clause currentlyEnabled(Ext_H) = false
function clause currentlyEnabled(Ext_Zicbom) = false
function clause currentlyEnabled(Ext_Zicboz) = false
function clause currentlyEnabled(Ext_Zkr) = false
function clause currentlyEnabled(Ext_Zicsr) = false
function clause currentlyEnabled(Ext_Zicntr) = false
